// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ChatID    int64              `json:"chat_id"`
	Paused    bool               `json:"paused"`
	ResumeAt  pgtype.Timestamptz `json:"resume_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SimpleMessage struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	ChatID    int64              `json:"chat_id"`
	CharCount int32              `json:"char_count"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
}

type User struct {
	UserID    int64              `json:"user_id"`
	Username  *string            `json:"username"`
	FirstSeen pgtype.Timestamptz `json:"first_seen"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
}

type UserOverride struct {
	ID            int64              `json:"id"`
	ChatID        int64              `json:"chat_id"`
	UserID        int64              `json:"user_id"`
	OverrideState *bool              `json:"override_state"`
	Reason        *string            `json:"reason"`
	CreatedBy     int64              `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type WindowSlot struct {
	ID             int32              `json:"id"`
	ChatID         int64              `json:"chat_id"`
	SlotID         string             `json:"slot_id"`
	CharLimit      int32              `json:"char_limit"`
	DurationValue  int32              `json:"duration_value"`
	DurationUnit   string             `json:"duration_unit"`
	WindowDuration int32              `json:"window_duration"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
