// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CleanupExpiredOverrides = `-- name: CleanupExpiredOverrides :exec
DELETE FROM user_overrides
WHERE expires_at IS NOT NULL AND expires_at < CURRENT_TIMESTAMP
`

// Remove expired overrides
func (q *Queries) CleanupExpiredOverrides(ctx context.Context) error {
	_, err := q.db.Exec(ctx, CleanupExpiredOverrides)
	return err
}

const CleanupOldMessages = `-- name: CleanupOldMessages :exec
DELETE FROM simple_messages
WHERE sent_at < NOW() - ($1 || ' seconds')::INTERVAL
`

// Delete messages older than retention period (cleanup job)
// Should be run periodically to prevent unbounded growth
func (q *Queries) CleanupOldMessages(ctx context.Context, dollar_1 *string) error {
	_, err := q.db.Exec(ctx, CleanupOldMessages, dollar_1)
	return err
}

const CreateDefaultWindows = `-- name: CreateDefaultWindows :exec
INSERT INTO window_slots (chat_id, slot_id, char_limit, duration_value, duration_unit, window_duration, enabled)
VALUES 
    ($1, 'a', 100, 1, 'minute', 60, TRUE),
    ($1, 'b', 1000, 1, 'hour', 3600, FALSE),
    ($1, 'c', 10000, 1, 'day', 86400, FALSE)
ON CONFLICT (chat_id, slot_id) DO NOTHING
`

// Initialize default windows for a new group
// Window A: 100 chars/1 minute (enabled by default)
// Window B: 1000 chars/1 hour (disabled by default)
// Window C: 10000 chars/1 day (disabled by default)
func (q *Queries) CreateDefaultWindows(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, CreateDefaultWindows, chatID)
	return err
}

const CreateSyncMetadata = `-- name: CreateSyncMetadata :one
INSERT INTO sync_metadata (
    chat_id,
    sync_status,
    next_sync_at
) VALUES (
    $1, 'pending', NOW() + INTERVAL '24 hours'
)
ON CONFLICT (chat_id) DO NOTHING
RETURNING id, chat_id, sync_status, last_sync_at, next_sync_at, created_at, updated_at, total_members, failed_attempts, last_error
`

// Initialize sync metadata for a new group
func (q *Queries) CreateSyncMetadata(ctx context.Context, chatID int64) (SyncMetadatum, error) {
	row := q.db.QueryRow(ctx, CreateSyncMetadata, chatID)
	var i SyncMetadatum
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SyncStatus,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalMembers,
		&i.FailedAttempts,
		&i.LastError,
	)
	return i, err
}

const EnsureGroup = `-- name: EnsureGroup :exec



INSERT INTO groups (chat_id)
VALUES ($1)
ON CONFLICT (chat_id) DO NOTHING
`

// ============================================================================
// LEGACY Statistics Queries (DISABLED - table 'messages' removed)
// ============================================================================
// LEGACY: GetGroupStats - table 'messages' removed
// ============================================================================
// Multi-Window Configuration Queries (Feature 006)
// ============================================================================
// Create group record if it doesn't exist (required for foreign key constraints)
func (q *Queries) EnsureGroup(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, EnsureGroup, chatID)
	return err
}

const EnsureGroupWithUsername = `-- name: EnsureGroupWithUsername :exec
INSERT INTO groups (chat_id, username)
VALUES ($1, $2)
ON CONFLICT (chat_id) DO UPDATE
SET username = CASE 
    WHEN EXCLUDED.username IS NOT NULL THEN EXCLUDED.username 
    ELSE groups.username 
END
`

type EnsureGroupWithUsernameParams struct {
	ChatID   int64   `json:"chat_id"`
	Username *string `json:"username"`
}

// Create or update group record with username (Feature 011: proactive group records)
func (q *Queries) EnsureGroupWithUsername(ctx context.Context, arg EnsureGroupWithUsernameParams) error {
	_, err := q.db.Exec(ctx, EnsureGroupWithUsername, arg.ChatID, arg.Username)
	return err
}

const EnsureUser = `-- name: EnsureUser :exec
INSERT INTO users (user_id, username, first_seen, last_seen)
VALUES ($1, $2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (user_id) DO UPDATE
SET username = EXCLUDED.username,
    last_seen = CURRENT_TIMESTAMP
`

type EnsureUserParams struct {
	UserID   int64   `json:"user_id"`
	Username *string `json:"username"`
}

// Create user record if it doesn't exist (required for foreign key constraints)
// Also updates username and last_seen on every call (for username harvesting)
func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) error {
	_, err := q.db.Exec(ctx, EnsureUser, arg.UserID, arg.Username)
	return err
}

const GetActiveMembersInGroup = `-- name: GetActiveMembersInGroup :many
SELECT u.user_id, u.username
FROM group_memberships gm
JOIN users u ON gm.user_id = u.user_id
WHERE gm.chat_id = $1 AND gm.status = 'active'
`

type GetActiveMembersInGroupRow struct {
	UserID   int64   `json:"user_id"`
	Username *string `json:"username"`
}

// Get all active members in a group
func (q *Queries) GetActiveMembersInGroup(ctx context.Context, chatID int64) ([]GetActiveMembersInGroupRow, error) {
	rows, err := q.db.Query(ctx, GetActiveMembersInGroup, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveMembersInGroupRow{}
	for rows.Next() {
		var i GetActiveMembersInGroupRow
		if err := rows.Scan(&i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllGroups = `-- name: GetAllGroups :many
SELECT chat_id FROM groups
ORDER BY created_at DESC
`

// Get all configured groups (simple messages design - no enabled column)
func (q *Queries) GetAllGroups(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, GetAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var chat_id int64
		if err := rows.Scan(&chat_id); err != nil {
			return nil, err
		}
		items = append(items, chat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllOverrides = `-- name: GetAllOverrides :many
SELECT user_id, override_state, reason, created_at, created_by, expires_at
FROM user_overrides
WHERE chat_id = $1
ORDER BY created_at DESC
`

type GetAllOverridesRow struct {
	UserID        int64              `json:"user_id"`
	OverrideState *bool              `json:"override_state"`
	Reason        *string            `json:"reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedBy     int64              `json:"created_by"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

// Get all manual overrides for a chat
func (q *Queries) GetAllOverrides(ctx context.Context, chatID int64) ([]GetAllOverridesRow, error) {
	rows, err := q.db.Query(ctx, GetAllOverrides, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllOverridesRow{}
	for rows.Next() {
		var i GetAllOverridesRow
		if err := rows.Scan(
			&i.UserID,
			&i.OverrideState,
			&i.Reason,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllWindows = `-- name: GetAllWindows :many
SELECT id, chat_id, slot_id, char_limit, duration_value, duration_unit, window_duration, enabled, created_at, updated_at FROM window_slots WHERE chat_id = $1 ORDER BY slot_id
`

// Get all windows for a chat (for /config command)
func (q *Queries) GetAllWindows(ctx context.Context, chatID int64) ([]WindowSlot, error) {
	rows, err := q.db.Query(ctx, GetAllWindows, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WindowSlot{}
	for rows.Next() {
		var i WindowSlot
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SlotID,
			&i.CharLimit,
			&i.DurationValue,
			&i.DurationUnit,
			&i.WindowDuration,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEnabledWindows = `-- name: GetEnabledWindows :many
SELECT id, slot_id, char_limit, duration_value, duration_unit, window_duration
FROM window_slots
WHERE chat_id = $1 AND enabled = TRUE
ORDER BY slot_id
`

type GetEnabledWindowsRow struct {
	ID             int32  `json:"id"`
	SlotID         string `json:"slot_id"`
	CharLimit      int32  `json:"char_limit"`
	DurationValue  int32  `json:"duration_value"`
	DurationUnit   string `json:"duration_unit"`
	WindowDuration int32  `json:"window_duration"`
}

// Get all enabled windows for evaluation
func (q *Queries) GetEnabledWindows(ctx context.Context, chatID int64) ([]GetEnabledWindowsRow, error) {
	rows, err := q.db.Query(ctx, GetEnabledWindows, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnabledWindowsRow{}
	for rows.Next() {
		var i GetEnabledWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.CharLimit,
			&i.DurationValue,
			&i.DurationUnit,
			&i.WindowDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetGroupByUsername = `-- name: GetGroupByUsername :one
SELECT chat_id, username, language
FROM groups
WHERE LOWER(username) = LOWER($1)
  AND username IS NOT NULL
  AND username != ''
`

type GetGroupByUsernameRow struct {
	ChatID   int64   `json:"chat_id"`
	Username *string `json:"username"`
	Language string  `json:"language"`
}

// Look up group by @username for group parameter parsing (Feature 008)
func (q *Queries) GetGroupByUsername(ctx context.Context, lower string) (GetGroupByUsernameRow, error) {
	row := q.db.QueryRow(ctx, GetGroupByUsername, lower)
	var i GetGroupByUsernameRow
	err := row.Scan(&i.ChatID, &i.Username, &i.Language)
	return i, err
}

const GetGroupConfig = `-- name: GetGroupConfig :one






SELECT chat_id, paused, resume_at, created_at, updated_at, language, username FROM groups
WHERE chat_id = $1
`

// ============================================================================
// LEGACY Restriction Management Queries (DISABLED - table removed in migration 000003)
// ============================================================================
// LEGACY: GetActiveRestriction - table 'restrictions' removed
// LEGACY: GetAllActiveRestrictions - table 'restrictions' removed
// LEGACY: CreateRestriction - table 'restrictions' removed
// LEGACY: UpdateRestriction - table 'restrictions' removed
// LEGACY: GetUserRestrictionHistory - table 'restrictions' removed
// LEGACY: GetRestrictedUsers - table 'restrictions' removed
// ============================================================================
// REMOVED: Exemption Queries (table removed in migration 000007)
// ============================================================================
// REMOVED: IsUserExempt - exemptions table removed (use user_overrides instead)
// REMOVED: RemoveExemption - exemptions table removed
// REMOVED: IsUserExemptFromWindow - exemptions table removed (see below)
// ============================================================================
// Warning State Management Queries
// ============================================================================
// LEGACY: GetWarningState - table 'warning_states' removed
// LEGACY: UpsertWarningState - table 'warning_states' removed
// LEGACY: DeleteOldWarningStates - table 'warning_states' removed
// LEGACY: DeleteUserWarningStates - table 'warning_states' removed
// ============================================================================
// Group Configuration Queries
// ============================================================================
// Get rate limit configuration for a group
func (q *Queries) GetGroupConfig(ctx context.Context, chatID int64) (Group, error) {
	row := q.db.QueryRow(ctx, GetGroupConfig, chatID)
	var i Group
	err := row.Scan(
		&i.ChatID,
		&i.Paused,
		&i.ResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
		&i.Username,
	)
	return i, err
}

const GetGroupLanguage = `-- name: GetGroupLanguage :one

SELECT language FROM groups
WHERE chat_id = $1
`

// ============================================================================
// Language Configuration Queries (Feature 007)
// ============================================================================
// Get the configured language for a group
func (q *Queries) GetGroupLanguage(ctx context.Context, chatID int64) (string, error) {
	row := q.db.QueryRow(ctx, GetGroupLanguage, chatID)
	var language string
	err := row.Scan(&language)
	return language, err
}

const GetGroupMembership = `-- name: GetGroupMembership :one



SELECT id, chat_id, user_id, status, joined_at, left_at, updated_at, is_admin, can_send_messages FROM group_memberships
WHERE chat_id = $1 AND user_id = $2
LIMIT 1
`

type GetGroupMembershipParams struct {
	ChatID int64 `json:"chat_id"`
	UserID int64 `json:"user_id"`
}

// ============================================================================
// LEGACY Queries (DISABLED - columns removed from groups table in migration 000003)
// ============================================================================
// LEGACY: GetChatLimit - columns 'char_limit', 'window_duration' removed from groups table
// LEGACY: SetChatLimit - columns removed from groups table
// ============================================================================
// Group Membership Tracking Queries (Feature 011)
// ============================================================================
// Get membership record for user in group
func (q *Queries) GetGroupMembership(ctx context.Context, arg GetGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, GetGroupMembership, arg.ChatID, arg.UserID)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.CanSendMessages,
	)
	return i, err
}

const GetGroupsNeedingSync = `-- name: GetGroupsNeedingSync :many
SELECT sm.id, sm.chat_id, sm.sync_status, sm.last_sync_at, sm.next_sync_at, sm.created_at, sm.updated_at, sm.total_members, sm.failed_attempts, sm.last_error, g.chat_id
FROM sync_metadata sm
JOIN groups g ON sm.chat_id = g.chat_id
WHERE sm.next_sync_at < NOW() 
  AND sm.sync_status != 'in_progress'
ORDER BY sm.next_sync_at ASC
LIMIT $1
`

type GetGroupsNeedingSyncRow struct {
	ID             int64              `json:"id"`
	ChatID         int64              `json:"chat_id"`
	SyncStatus     string             `json:"sync_status"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	NextSyncAt     pgtype.Timestamptz `json:"next_sync_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TotalMembers   *int32             `json:"total_members"`
	FailedAttempts *int32             `json:"failed_attempts"`
	LastError      *string            `json:"last_error"`
	ChatID_2       int64              `json:"chat_id_2"`
}

// Get groups that need periodic sync (next_sync_at < NOW)
func (q *Queries) GetGroupsNeedingSync(ctx context.Context, limit int32) ([]GetGroupsNeedingSyncRow, error) {
	rows, err := q.db.Query(ctx, GetGroupsNeedingSync, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupsNeedingSyncRow{}
	for rows.Next() {
		var i GetGroupsNeedingSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SyncStatus,
			&i.LastSyncAt,
			&i.NextSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalMembers,
			&i.FailedAttempts,
			&i.LastError,
			&i.ChatID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRecentSyncEvents = `-- name: GetRecentSyncEvents :many
SELECT se.id, se.metadata_id, se.event_type, se.started_at, se.completed_at, se.status, se.error_message, se.members_processed, se.members_added, se.members_updated, se.members_removed, sm.chat_id
FROM sync_events se
JOIN sync_metadata sm ON se.metadata_id = sm.id
ORDER BY se.started_at DESC
LIMIT $1
`

type GetRecentSyncEventsRow struct {
	ID               int64              `json:"id"`
	MetadataID       int64              `json:"metadata_id"`
	EventType        string             `json:"event_type"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	Status           string             `json:"status"`
	ErrorMessage     *string            `json:"error_message"`
	MembersProcessed *int32             `json:"members_processed"`
	MembersAdded     *int32             `json:"members_added"`
	MembersUpdated   *int32             `json:"members_updated"`
	MembersRemoved   *int32             `json:"members_removed"`
	ChatID           int64              `json:"chat_id"`
}

// Get recent sync events for monitoring (last N events)
func (q *Queries) GetRecentSyncEvents(ctx context.Context, limit int32) ([]GetRecentSyncEventsRow, error) {
	rows, err := q.db.Query(ctx, GetRecentSyncEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentSyncEventsRow{}
	for rows.Next() {
		var i GetRecentSyncEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.MetadataID,
			&i.EventType,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.ErrorMessage,
			&i.MembersProcessed,
			&i.MembersAdded,
			&i.MembersUpdated,
			&i.MembersRemoved,
			&i.ChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStaleGroupMemberships = `-- name: GetStaleGroupMemberships :many
SELECT gm.id, gm.chat_id, gm.user_id, gm.status, gm.joined_at, gm.left_at, gm.updated_at, gm.is_admin, gm.can_send_messages, g.chat_id
FROM group_memberships gm
JOIN groups g ON gm.chat_id = g.chat_id
WHERE gm.status = 'active' 
  AND gm.updated_at < NOW() - INTERVAL '48 hours'
`

type GetStaleGroupMembershipsRow struct {
	ID              int64              `json:"id"`
	ChatID          int64              `json:"chat_id"`
	UserID          int64              `json:"user_id"`
	Status          string             `json:"status"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
	LeftAt          pgtype.Timestamptz `json:"left_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	IsAdmin         bool               `json:"is_admin"`
	CanSendMessages bool               `json:"can_send_messages"`
	ChatID_2        int64              `json:"chat_id_2"`
}

// Find memberships not updated in last 48 hours (for metrics)
func (q *Queries) GetStaleGroupMemberships(ctx context.Context) ([]GetStaleGroupMembershipsRow, error) {
	rows, err := q.db.Query(ctx, GetStaleGroupMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleGroupMembershipsRow{}
	for rows.Next() {
		var i GetStaleGroupMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.UpdatedAt,
			&i.IsAdmin,
			&i.CanSendMessages,
			&i.ChatID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id FROM users
WHERE LOWER(username) = LOWER($1) 
  AND username != ''
`

// Resolve @username to user_id (case-insensitive lookup)
func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRow(ctx, GetUserByUsername, lower)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const GetUserLanguage = `-- name: GetUserLanguage :one
SELECT language FROM users
WHERE user_id = $1
`

// Retrieve user's language preference for private responses (Feature 008)
func (q *Queries) GetUserLanguage(ctx context.Context, userID int64) (*string, error) {
	row := q.db.QueryRow(ctx, GetUserLanguage, userID)
	var language *string
	err := row.Scan(&language)
	return language, err
}

const GetUserOverride = `-- name: GetUserOverride :one



SELECT override_state, reason, expires_at FROM user_overrides
WHERE chat_id = $1 AND user_id = $2
`

type GetUserOverrideParams struct {
	ChatID int64 `json:"chat_id"`
	UserID int64 `json:"user_id"`
}

type GetUserOverrideRow struct {
	OverrideState *bool              `json:"override_state"`
	Reason        *string            `json:"reason"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

// GetMostViolatedWindow removed - no restriction table in simple design
// Violations are not tracked; messages are just deleted when over limit
// ============================================================================
// REMOVED: Multi-Window Exemption Queries (table removed in migration 000007)
// ============================================================================
// REMOVED: IsUserExemptFromWindow - exemptions table removed
// Note: Use user_overrides table with /override command instead
// ============================================================================
// User Overrides (3-State Manual Control)
// ============================================================================
// Get manual override state for a user (NULL=follow rate limiter, TRUE=whitelist, FALSE=blacklist)
func (q *Queries) GetUserOverride(ctx context.Context, arg GetUserOverrideParams) (GetUserOverrideRow, error) {
	row := q.db.QueryRow(ctx, GetUserOverride, arg.ChatID, arg.UserID)
	var i GetUserOverrideRow
	err := row.Scan(&i.OverrideState, &i.Reason, &i.ExpiresAt)
	return i, err
}

const GetUserWindowStats = `-- name: GetUserWindowStats :many
SELECT 
    wsl.slot_id,
    wsl.char_limit,
    wsl.duration_value,
    wsl.duration_unit,
    wsl.window_duration,
    wsl.enabled,
    COALESCE(SUM(m.char_count), 0)::INTEGER as current_usage
FROM window_slots wsl
LEFT JOIN simple_messages m ON 
    m.chat_id = wsl.chat_id 
    AND m.user_id = $1
    AND m.sent_at > NOW() - (wsl.window_duration || ' seconds')::INTERVAL
WHERE wsl.chat_id = $2
GROUP BY wsl.slot_id, wsl.char_limit, wsl.duration_value, wsl.duration_unit, wsl.window_duration, wsl.enabled
ORDER BY wsl.slot_id
`

type GetUserWindowStatsParams struct {
	UserID int64 `json:"user_id"`
	ChatID int64 `json:"chat_id"`
}

type GetUserWindowStatsRow struct {
	SlotID         string `json:"slot_id"`
	CharLimit      int32  `json:"char_limit"`
	DurationValue  int32  `json:"duration_value"`
	DurationUnit   string `json:"duration_unit"`
	WindowDuration int32  `json:"window_duration"`
	Enabled        bool   `json:"enabled"`
	CurrentUsage   int32  `json:"current_usage"`
}

// Get current usage statistics for all windows for a user (for /mystatus command)
// All windows share the same message log, each window calculates usage based on its time window
func (q *Queries) GetUserWindowStats(ctx context.Context, arg GetUserWindowStatsParams) ([]GetUserWindowStatsRow, error) {
	rows, err := q.db.Query(ctx, GetUserWindowStats, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserWindowStatsRow{}
	for rows.Next() {
		var i GetUserWindowStatsRow
		if err := rows.Scan(
			&i.SlotID,
			&i.CharLimit,
			&i.DurationValue,
			&i.DurationUnit,
			&i.WindowDuration,
			&i.Enabled,
			&i.CurrentUsage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUsernameByUserID = `-- name: GetUsernameByUserID :one
SELECT username FROM users
WHERE user_id = $1
`

// Reverse lookup: get username from user_id (for display purposes)
func (q *Queries) GetUsernameByUserID(ctx context.Context, userID int64) (*string, error) {
	row := q.db.QueryRow(ctx, GetUsernameByUserID, userID)
	var username *string
	err := row.Scan(&username)
	return username, err
}

const GetWindowSlot = `-- name: GetWindowSlot :one
SELECT id, chat_id, slot_id, char_limit, duration_value, duration_unit, window_duration, enabled, created_at, updated_at
FROM window_slots
WHERE chat_id = $1 AND slot_id = $2
`

type GetWindowSlotParams struct {
	ChatID int64  `json:"chat_id"`
	SlotID string `json:"slot_id"`
}

// Get specific window configuration
func (q *Queries) GetWindowSlot(ctx context.Context, arg GetWindowSlotParams) (WindowSlot, error) {
	row := q.db.QueryRow(ctx, GetWindowSlot, arg.ChatID, arg.SlotID)
	var i WindowSlot
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SlotID,
		&i.CharLimit,
		&i.DurationValue,
		&i.DurationUnit,
		&i.WindowDuration,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetWindowStats = `-- name: GetWindowStats :one




SELECT 
    COUNT(DISTINCT m.user_id) AS active_users,
    COALESCE(AVG(m.char_count), 0)::INTEGER AS avg_usage
FROM simple_messages m
JOIN window_slots ws ON ws.chat_id = m.chat_id
WHERE m.chat_id = $1 AND ws.slot_id = $2
  AND m.sent_at > NOW() - (ws.window_duration || ' seconds')::INTERVAL
`

type GetWindowStatsParams struct {
	ChatID int64  `json:"chat_id"`
	SlotID string `json:"slot_id"`
}

type GetWindowStatsRow struct {
	ActiveUsers int64 `json:"active_users"`
	AvgUsage    int32 `json:"avg_usage"`
}

// Warning levels are now calculated on-demand from current usage
// No need to store them in database
// GetAllWindowStates removed - replaced by GetUserWindowStats which uses messages table
// ============================================================================
// Multi-Window Evaluation (No Restriction Table Needed!)
// ============================================================================
// With simple design, restriction is calculated on-demand:
// User is "restricted" when: current_usage + new_message_length > limit
// No need to store restriction state!
// ============================================================================
// Multi-Window Statistics Queries
// ============================================================================
// Get statistics for a specific window from simple_messages table
// All windows share the same message log, filtered by the window's time range
func (q *Queries) GetWindowStats(ctx context.Context, arg GetWindowStatsParams) (GetWindowStatsRow, error) {
	row := q.db.QueryRow(ctx, GetWindowStats, arg.ChatID, arg.SlotID)
	var i GetWindowStatsRow
	err := row.Scan(&i.ActiveUsers, &i.AvgUsage)
	return i, err
}

const GetWindowUsage = `-- name: GetWindowUsage :one
SELECT COALESCE(SUM(char_count), 0)::INTEGER as total_chars
FROM simple_messages
WHERE user_id = $1 
  AND chat_id = $2 
  AND sent_at > NOW() - ($3 || ' seconds')::INTERVAL
`

type GetWindowUsageParams struct {
	UserID  int64   `json:"user_id"`
	ChatID  int64   `json:"chat_id"`
	Column3 *string `json:"column_3"`
}

// Calculate current usage for a window using sliding window
// Returns sum of char_count for all messages within the time window
// All windows share the same message log, filtered by time window
func (q *Queries) GetWindowUsage(ctx context.Context, arg GetWindowUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, GetWindowUsage, arg.UserID, arg.ChatID, arg.Column3)
	var total_chars int32
	err := row.Scan(&total_chars)
	return total_chars, err
}

const IsGroupPaused = `-- name: IsGroupPaused :one
SELECT paused, resume_at FROM groups
WHERE chat_id = $1
`

type IsGroupPausedRow struct {
	Paused   bool               `json:"paused"`
	ResumeAt pgtype.Timestamptz `json:"resume_at"`
}

// Check if a group's rate limiting is paused
func (q *Queries) IsGroupPaused(ctx context.Context, chatID int64) (IsGroupPausedRow, error) {
	row := q.db.QueryRow(ctx, IsGroupPaused, chatID)
	var i IsGroupPausedRow
	err := row.Scan(&i.Paused, &i.ResumeAt)
	return i, err
}

const ListAllGroupLanguages = `-- name: ListAllGroupLanguages :many
SELECT chat_id, language FROM groups
ORDER BY chat_id
`

type ListAllGroupLanguagesRow struct {
	ChatID   int64  `json:"chat_id"`
	Language string `json:"language"`
}

// Get language preferences for all groups (for cache initialization)
func (q *Queries) ListAllGroupLanguages(ctx context.Context) ([]ListAllGroupLanguagesRow, error) {
	rows, err := q.db.Query(ctx, ListAllGroupLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllGroupLanguagesRow{}
	for rows.Next() {
		var i ListAllGroupLanguagesRow
		if err := rows.Scan(&i.ChatID, &i.Language); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RecordMessage = `-- name: RecordMessage :exec


INSERT INTO simple_messages (user_id, chat_id, char_count, sent_at)
VALUES ($1, $2, $3, NOW())
`

type RecordMessageParams struct {
	UserID    int64 `json:"user_id"`
	ChatID    int64 `json:"chat_id"`
	CharCount int32 `json:"char_count"`
}

// ============================================================================
// Multi-Window State Tracking Queries
// ============================================================================
// GetWindowState removed - no longer needed with simple messages design
// Current usage is calculated on-demand via GetWindowUsage
// Record a message for sliding window calculation (one row per message, shared across all windows)
func (q *Queries) RecordMessage(ctx context.Context, arg RecordMessageParams) error {
	_, err := q.db.Exec(ctx, RecordMessage, arg.UserID, arg.ChatID, arg.CharCount)
	return err
}

const RecordSyncEvent = `-- name: RecordSyncEvent :one
INSERT INTO sync_events (
    metadata_id,
    event_type,
    started_at,
    completed_at,
    status,
    error_message,
    members_processed,
    members_added,
    members_updated,
    members_removed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, metadata_id, event_type, started_at, completed_at, status, error_message, members_processed, members_added, members_updated, members_removed
`

type RecordSyncEventParams struct {
	MetadataID       int64              `json:"metadata_id"`
	EventType        string             `json:"event_type"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	Status           string             `json:"status"`
	ErrorMessage     *string            `json:"error_message"`
	MembersProcessed *int32             `json:"members_processed"`
	MembersAdded     *int32             `json:"members_added"`
	MembersUpdated   *int32             `json:"members_updated"`
	MembersRemoved   *int32             `json:"members_removed"`
}

// Create audit trail entry for sync operation
func (q *Queries) RecordSyncEvent(ctx context.Context, arg RecordSyncEventParams) (SyncEvent, error) {
	row := q.db.QueryRow(ctx, RecordSyncEvent,
		arg.MetadataID,
		arg.EventType,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Status,
		arg.ErrorMessage,
		arg.MembersProcessed,
		arg.MembersAdded,
		arg.MembersUpdated,
		arg.MembersRemoved,
	)
	var i SyncEvent
	err := row.Scan(
		&i.ID,
		&i.MetadataID,
		&i.EventType,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.ErrorMessage,
		&i.MembersProcessed,
		&i.MembersAdded,
		&i.MembersUpdated,
		&i.MembersRemoved,
	)
	return i, err
}

const RemoveUserOverride = `-- name: RemoveUserOverride :exec
DELETE FROM user_overrides
WHERE chat_id = $1 AND user_id = $2
`

type RemoveUserOverrideParams struct {
	ChatID int64 `json:"chat_id"`
	UserID int64 `json:"user_id"`
}

// Remove manual override (return to rate limiter control)
func (q *Queries) RemoveUserOverride(ctx context.Context, arg RemoveUserOverrideParams) error {
	_, err := q.db.Exec(ctx, RemoveUserOverride, arg.ChatID, arg.UserID)
	return err
}

const ResetWindowMessages = `-- name: ResetWindowMessages :exec
DELETE FROM simple_messages
WHERE user_id = $1 AND chat_id = $2
`

type ResetWindowMessagesParams struct {
	UserID int64 `json:"user_id"`
	ChatID int64 `json:"chat_id"`
}

// Reset all messages for a user in a chat (affects all windows)
func (q *Queries) ResetWindowMessages(ctx context.Context, arg ResetWindowMessagesParams) error {
	_, err := q.db.Exec(ctx, ResetWindowMessages, arg.UserID, arg.ChatID)
	return err
}

const ResetWindowMessagesForAll = `-- name: ResetWindowMessagesForAll :exec
DELETE FROM simple_messages
WHERE chat_id = $1
`

// Reset all messages for all users in a chat (affects all windows)
func (q *Queries) ResetWindowMessagesForAll(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, ResetWindowMessagesForAll, chatID)
	return err
}

const SetGroupLanguage = `-- name: SetGroupLanguage :exec
UPDATE groups
SET language = $2, updated_at = NOW()
WHERE chat_id = $1
`

type SetGroupLanguageParams struct {
	ChatID   int64  `json:"chat_id"`
	Language string `json:"language"`
}

// Set the language preference for a group
func (q *Queries) SetGroupLanguage(ctx context.Context, arg SetGroupLanguageParams) error {
	_, err := q.db.Exec(ctx, SetGroupLanguage, arg.ChatID, arg.Language)
	return err
}

const SetGroupPaused = `-- name: SetGroupPaused :exec

UPDATE groups
SET paused = $2,
    resume_at = $3,
    updated_at = NOW()
WHERE chat_id = $1
`

type SetGroupPausedParams struct {
	ChatID   int64              `json:"chat_id"`
	Paused   bool               `json:"paused"`
	ResumeAt pgtype.Timestamptz `json:"resume_at"`
}

// LEGACY: UpsertGroupConfig - columns char_limit, duration_value, duration_unit, window_duration removed from groups table
// Pause or unpause rate limiting for a group
func (q *Queries) SetGroupPaused(ctx context.Context, arg SetGroupPausedParams) error {
	_, err := q.db.Exec(ctx, SetGroupPaused, arg.ChatID, arg.Paused, arg.ResumeAt)
	return err
}

const SetUserLanguage = `-- name: SetUserLanguage :exec
UPDATE users
SET language = $2
WHERE user_id = $1
`

type SetUserLanguageParams struct {
	UserID   int64   `json:"user_id"`
	Language *string `json:"language"`
}

// Set the language preference for a user (Feature 009)
func (q *Queries) SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error {
	_, err := q.db.Exec(ctx, SetUserLanguage, arg.UserID, arg.Language)
	return err
}

const SetUserOverride = `-- name: SetUserOverride :exec
INSERT INTO user_overrides (chat_id, user_id, override_state, reason, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (chat_id, user_id) 
DO UPDATE SET 
    override_state = EXCLUDED.override_state,
    reason = EXCLUDED.reason,
    created_by = EXCLUDED.created_by,
    expires_at = EXCLUDED.expires_at,
    created_at = CURRENT_TIMESTAMP
`

type SetUserOverrideParams struct {
	ChatID        int64              `json:"chat_id"`
	UserID        int64              `json:"user_id"`
	OverrideState *bool              `json:"override_state"`
	Reason        *string            `json:"reason"`
	CreatedBy     int64              `json:"created_by"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

// Set manual override state for a user
func (q *Queries) SetUserOverride(ctx context.Context, arg SetUserOverrideParams) error {
	_, err := q.db.Exec(ctx, SetUserOverride,
		arg.ChatID,
		arg.UserID,
		arg.OverrideState,
		arg.Reason,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const SetWindowEnabled = `-- name: SetWindowEnabled :exec
UPDATE window_slots
SET enabled = $3, updated_at = NOW()
WHERE chat_id = $1 AND slot_id = $2
`

type SetWindowEnabledParams struct {
	ChatID  int64  `json:"chat_id"`
	SlotID  string `json:"slot_id"`
	Enabled bool   `json:"enabled"`
}

// Enable or disable a window (/enablewindow, /disablewindow commands)
func (q *Queries) SetWindowEnabled(ctx context.Context, arg SetWindowEnabledParams) error {
	_, err := q.db.Exec(ctx, SetWindowEnabled, arg.ChatID, arg.SlotID, arg.Enabled)
	return err
}

const UpdateSyncMetadata = `-- name: UpdateSyncMetadata :exec
UPDATE sync_metadata SET
    sync_status = $2,
    last_sync_at = $3,
    next_sync_at = $4,
    total_members = $5,
    failed_attempts = $6,
    last_error = $7
WHERE chat_id = $1
`

type UpdateSyncMetadataParams struct {
	ChatID         int64              `json:"chat_id"`
	SyncStatus     string             `json:"sync_status"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	NextSyncAt     pgtype.Timestamptz `json:"next_sync_at"`
	TotalMembers   *int32             `json:"total_members"`
	FailedAttempts *int32             `json:"failed_attempts"`
	LastError      *string            `json:"last_error"`
}

// Update sync metadata after sync operation
func (q *Queries) UpdateSyncMetadata(ctx context.Context, arg UpdateSyncMetadataParams) error {
	_, err := q.db.Exec(ctx, UpdateSyncMetadata,
		arg.ChatID,
		arg.SyncStatus,
		arg.LastSyncAt,
		arg.NextSyncAt,
		arg.TotalMembers,
		arg.FailedAttempts,
		arg.LastError,
	)
	return err
}

const UpdateWindowSlot = `-- name: UpdateWindowSlot :exec
INSERT INTO window_slots (chat_id, slot_id, char_limit, duration_value, duration_unit, window_duration, enabled, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT (chat_id, slot_id) 
DO UPDATE SET 
    char_limit = EXCLUDED.char_limit,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    window_duration = EXCLUDED.window_duration,
    enabled = EXCLUDED.enabled,
    updated_at = NOW()
`

type UpdateWindowSlotParams struct {
	ChatID         int64  `json:"chat_id"`
	SlotID         string `json:"slot_id"`
	CharLimit      int32  `json:"char_limit"`
	DurationValue  int32  `json:"duration_value"`
	DurationUnit   string `json:"duration_unit"`
	WindowDuration int32  `json:"window_duration"`
	Enabled        bool   `json:"enabled"`
}

// Update window configuration (/setwindow command)
func (q *Queries) UpdateWindowSlot(ctx context.Context, arg UpdateWindowSlotParams) error {
	_, err := q.db.Exec(ctx, UpdateWindowSlot,
		arg.ChatID,
		arg.SlotID,
		arg.CharLimit,
		arg.DurationValue,
		arg.DurationUnit,
		arg.WindowDuration,
		arg.Enabled,
	)
	return err
}

const UpsertGroupMembership = `-- name: UpsertGroupMembership :one
INSERT INTO group_memberships (
    chat_id,
    user_id,
    status,
    joined_at,
    left_at,
    is_admin,
    can_send_messages,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
ON CONFLICT (chat_id, user_id) DO UPDATE SET
    status = EXCLUDED.status,
    left_at = EXCLUDED.left_at,
    is_admin = EXCLUDED.is_admin,
    can_send_messages = EXCLUDED.can_send_messages,
    updated_at = NOW()
WHERE group_memberships.updated_at < EXCLUDED.updated_at
RETURNING id, chat_id, user_id, status, joined_at, left_at, updated_at, is_admin, can_send_messages
`

type UpsertGroupMembershipParams struct {
	ChatID          int64              `json:"chat_id"`
	UserID          int64              `json:"user_id"`
	Status          string             `json:"status"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
	LeftAt          pgtype.Timestamptz `json:"left_at"`
	IsAdmin         bool               `json:"is_admin"`
	CanSendMessages bool               `json:"can_send_messages"`
}

// Insert or update membership record (idempotent)
func (q *Queries) UpsertGroupMembership(ctx context.Context, arg UpsertGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, UpsertGroupMembership,
		arg.ChatID,
		arg.UserID,
		arg.Status,
		arg.JoinedAt,
		arg.LeftAt,
		arg.IsAdmin,
		arg.CanSendMessages,
	)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.CanSendMessages,
	)
	return i, err
}

const UpsertUser = `-- name: UpsertUser :one




INSERT INTO users (user_id, username, first_seen, last_seen)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (user_id) DO UPDATE
SET username = EXCLUDED.username,
    last_seen = NOW()
RETURNING user_id, username, first_seen, last_seen, language
`

type UpsertUserParams struct {
	UserID   int64   `json:"user_id"`
	Username *string `json:"username"`
}

// Complete SQLC queries for all Storage interface methods
// ============================================================================
// LEGACY Message Tracking Queries (DISABLED - table removed in migration 000003)
// ============================================================================
// LEGACY: GetUserCurrentUsage - table 'messages' removed
// LEGACY: StoreMessage - table 'messages' removed
// LEGACY: DeleteOldMessages - table 'messages' removed
// LEGACY: GetUserMessages - table 'messages' removed
// LEGACY: DeleteUserMessages - table 'messages' removed
// ============================================================================
// User Management Queries
// ============================================================================
// Create or update a user record
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, UpsertUser, arg.UserID, arg.Username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.FirstSeen,
		&i.LastSeen,
		&i.Language,
	)
	return i, err
}
