// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Remove expired overrides
	CleanupExpiredOverrides(ctx context.Context) error
	// Delete messages older than retention period (cleanup job)
	// Should be run periodically to prevent unbounded growth
	CleanupOldMessages(ctx context.Context, dollar_1 *string) error
	// Initialize default windows for a new group
	// Window A: 100 chars/1 minute (enabled by default)
	// Window B: 1000 chars/1 hour (disabled by default)
	// Window C: 10000 chars/1 day (disabled by default)
	CreateDefaultWindows(ctx context.Context, chatID int64) error
	// ============================================================================
	// LEGACY Statistics Queries (DISABLED - table 'messages' removed)
	// ============================================================================
	// LEGACY: GetGroupStats - table 'messages' removed
	// ============================================================================
	// Multi-Window Configuration Queries (Feature 006)
	// ============================================================================
	// Create group record if it doesn't exist (required for foreign key constraints)
	EnsureGroup(ctx context.Context, chatID int64) error
	// Create user record if it doesn't exist (required for foreign key constraints)
	// Also updates username and last_seen on every call (for username harvesting)
	EnsureUser(ctx context.Context, arg EnsureUserParams) error
	// Get all configured groups (simple messages design - no enabled column)
	GetAllGroups(ctx context.Context) ([]int64, error)
	// Get all manual overrides for a chat
	GetAllOverrides(ctx context.Context, chatID int64) ([]GetAllOverridesRow, error)
	// Get all windows for a chat (for /showwindows command)
	GetAllWindows(ctx context.Context, chatID int64) ([]WindowSlot, error)
	// Get all enabled windows for evaluation
	GetEnabledWindows(ctx context.Context, chatID int64) ([]GetEnabledWindowsRow, error)
	// ============================================================================
	// LEGACY Restriction Management Queries (DISABLED - table removed in migration 000003)
	// ============================================================================
	// LEGACY: GetActiveRestriction - table 'restrictions' removed
	// LEGACY: GetAllActiveRestrictions - table 'restrictions' removed
	// LEGACY: CreateRestriction - table 'restrictions' removed
	// LEGACY: UpdateRestriction - table 'restrictions' removed
	// LEGACY: GetUserRestrictionHistory - table 'restrictions' removed
	// LEGACY: GetRestrictedUsers - table 'restrictions' removed
	// ============================================================================
	// REMOVED: Exemption Queries (table removed in migration 000007)
	// ============================================================================
	// REMOVED: IsUserExempt - exemptions table removed (use user_overrides instead)
	// REMOVED: RemoveExemption - exemptions table removed
	// REMOVED: IsUserExemptFromWindow - exemptions table removed (see below)
	// ============================================================================
	// Warning State Management Queries
	// ============================================================================
	// LEGACY: GetWarningState - table 'warning_states' removed
	// LEGACY: UpsertWarningState - table 'warning_states' removed
	// LEGACY: DeleteOldWarningStates - table 'warning_states' removed
	// LEGACY: DeleteUserWarningStates - table 'warning_states' removed
	// ============================================================================
	// Group Configuration Queries
	// ============================================================================
	// Get rate limit configuration for a group
	GetGroupConfig(ctx context.Context, chatID int64) (Group, error)
	// Resolve @username to user_id (case-insensitive lookup)
	GetUserByUsername(ctx context.Context, lower string) (int64, error)
	// GetMostViolatedWindow removed - no restriction table in simple design
	// Violations are not tracked; messages are just deleted when over limit
	// ============================================================================
	// REMOVED: Multi-Window Exemption Queries (table removed in migration 000007)
	// ============================================================================
	// REMOVED: IsUserExemptFromWindow - exemptions table removed
	// Note: Use user_overrides table with /override command instead
	// ============================================================================
	// User Overrides (3-State Manual Control)
	// ============================================================================
	// Get manual override state for a user (NULL=follow rate limiter, TRUE=whitelist, FALSE=blacklist)
	GetUserOverride(ctx context.Context, arg GetUserOverrideParams) (GetUserOverrideRow, error)
	// Get current usage statistics for all windows for a user (for /mystatus command)
	// All windows share the same message log, each window calculates usage based on its time window
	GetUserWindowStats(ctx context.Context, arg GetUserWindowStatsParams) ([]GetUserWindowStatsRow, error)
	// Reverse lookup: get username from user_id (for display purposes)
	GetUsernameByUserID(ctx context.Context, userID int64) (*string, error)
	// Get specific window configuration
	GetWindowSlot(ctx context.Context, arg GetWindowSlotParams) (WindowSlot, error)
	// Warning levels are now calculated on-demand from current usage
	// No need to store them in database
	// GetAllWindowStates removed - replaced by GetUserWindowStats which uses messages table
	// ============================================================================
	// Multi-Window Evaluation (No Restriction Table Needed!)
	// ============================================================================
	// With simple design, restriction is calculated on-demand:
	// User is "restricted" when: current_usage + new_message_length > limit
	// No need to store restriction state!
	// ============================================================================
	// Multi-Window Statistics Queries
	// ============================================================================
	// Get statistics for a specific window from simple_messages table
	// All windows share the same message log, filtered by the window's time range
	GetWindowStats(ctx context.Context, arg GetWindowStatsParams) (GetWindowStatsRow, error)
	// Calculate current usage for a window using sliding window
	// Returns sum of char_count for all messages within the time window
	// All windows share the same message log, filtered by time window
	GetWindowUsage(ctx context.Context, arg GetWindowUsageParams) (int32, error)
	// Check if a group's rate limiting is paused
	IsGroupPaused(ctx context.Context, chatID int64) (IsGroupPausedRow, error)
	// ============================================================================
	// Multi-Window State Tracking Queries
	// ============================================================================
	// GetWindowState removed - no longer needed with simple messages design
	// Current usage is calculated on-demand via GetWindowUsage
	// Record a message for sliding window calculation (one row per message, shared across all windows)
	RecordMessage(ctx context.Context, arg RecordMessageParams) error
	// Remove manual override (return to rate limiter control)
	RemoveUserOverride(ctx context.Context, arg RemoveUserOverrideParams) error
	// Reset all messages for a user in a chat (affects all windows)
	ResetWindowMessages(ctx context.Context, arg ResetWindowMessagesParams) error
	// Reset all messages for all users in a chat (affects all windows)
	ResetWindowMessagesForAll(ctx context.Context, chatID int64) error
	// LEGACY: UpsertGroupConfig - columns char_limit, duration_value, duration_unit, window_duration removed from groups table
	// Pause or unpause rate limiting for a group
	SetGroupPaused(ctx context.Context, arg SetGroupPausedParams) error
	// Set manual override state for a user
	SetUserOverride(ctx context.Context, arg SetUserOverrideParams) error
	// Enable or disable a window (/enablewindow, /disablewindow commands)
	SetWindowEnabled(ctx context.Context, arg SetWindowEnabledParams) error
	// Update window configuration (/setwindow command)
	UpdateWindowSlot(ctx context.Context, arg UpdateWindowSlotParams) error
	// Complete SQLC queries for all Storage interface methods
	// ============================================================================
	// LEGACY Message Tracking Queries (DISABLED - table removed in migration 000003)
	// ============================================================================
	// LEGACY: GetUserCurrentUsage - table 'messages' removed
	// LEGACY: StoreMessage - table 'messages' removed
	// LEGACY: DeleteOldMessages - table 'messages' removed
	// LEGACY: GetUserMessages - table 'messages' removed
	// LEGACY: DeleteUserMessages - table 'messages' removed
	// ============================================================================
	// User Management Queries
	// ============================================================================
	// Create or update a user record
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
