// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Remove expired overrides
	CleanupExpiredOverrides(ctx context.Context) error
	// Delete messages older than retention period (cleanup job)
	// Should be run periodically to prevent unbounded growth
	CleanupOldMessages(ctx context.Context, dollar_1 *string) error
	// Count total active groups for pagination calculation
	// Supports FR-011 (pagination) from Feature 013 specification
	CountUserGroups(ctx context.Context, userID int64) (int64, error)
	// Initialize default windows for a new group
	// Window A: 100 chars/1 minute (enabled by default)
	// Window B: 1000 chars/1 hour (disabled by default)
	// Window C: 10000 chars/1 day (disabled by default)
	CreateDefaultWindows(ctx context.Context, chatID int64) error
	// Initialize sync metadata for a new group (upserts to handle existing records)
	CreateSyncMetadata(ctx context.Context, chatID int64) (SyncMetadatum, error)
	// ============================================================================
	// LEGACY Statistics Queries (DISABLED - table 'messages' removed)
	// ============================================================================
	// LEGACY: GetGroupStats - table 'messages' removed
	// ============================================================================
	// Multi-Window Configuration Queries (Feature 006)
	// ============================================================================
	// Create group record if it doesn't exist (required for foreign key constraints)
	EnsureGroup(ctx context.Context, chatID int64) error
	// Create or update group record with both username and title (Feature 014: unified metadata upsert)
	// This replaces the broken EnsureGroupWithUsername and EnsureGroupWithTitle queries that caused data corruption
	EnsureGroupMetadata(ctx context.Context, arg EnsureGroupMetadataParams) error
	// Create user record if it doesn't exist (required for foreign key constraints)
	// Also updates username and last_seen on every call (for username harvesting)
	EnsureUser(ctx context.Context, arg EnsureUserParams) error
	// Get all active members in a group
	GetActiveMembersInGroup(ctx context.Context, chatID int64) ([]GetActiveMembersInGroupRow, error)
	// Get all configured groups (simple messages design - no enabled column)
	GetAllGroups(ctx context.Context) ([]int64, error)
	// Get all manual overrides for a chat
	GetAllOverrides(ctx context.Context, chatID int64) ([]GetAllOverridesRow, error)
	// Get all windows for a chat (for /config command)
	GetAllWindows(ctx context.Context, chatID int64) ([]WindowSlot, error)
	// Get all enabled windows for evaluation
	GetEnabledWindows(ctx context.Context, chatID int64) ([]GetEnabledWindowsRow, error)
	// Get group by chat_id - Feature 014: unified resolution
	GetGroupByChatID(ctx context.Context, chatID int64) (GetGroupByChatIDRow, error)
	// Get group by @username (case-insensitive) - Feature 014: unified resolution
	GetGroupByUsername(ctx context.Context, lower string) (GetGroupByUsernameRow, error)
	// ============================================================================
	// LEGACY Restriction Management Queries (DISABLED - table removed in migration 000003)
	// ============================================================================
	// LEGACY: GetActiveRestriction - table 'restrictions' removed
	// LEGACY: GetAllActiveRestrictions - table 'restrictions' removed
	// LEGACY: CreateRestriction - table 'restrictions' removed
	// LEGACY: UpdateRestriction - table 'restrictions' removed
	// LEGACY: GetUserRestrictionHistory - table 'restrictions' removed
	// LEGACY: GetRestrictedUsers - table 'restrictions' removed
	// ============================================================================
	// REMOVED: Exemption Queries (table removed in migration 000007)
	// ============================================================================
	// REMOVED: IsUserExempt - exemptions table removed (use user_overrides instead)
	// REMOVED: RemoveExemption - exemptions table removed
	// REMOVED: IsUserExemptFromWindow - exemptions table removed (see below)
	// ============================================================================
	// Warning State Management Queries
	// ============================================================================
	// LEGACY: GetWarningState - table 'warning_states' removed
	// LEGACY: UpsertWarningState - table 'warning_states' removed
	// LEGACY: DeleteOldWarningStates - table 'warning_states' removed
	// LEGACY: DeleteUserWarningStates - table 'warning_states' removed
	// ============================================================================
	// Group Configuration Queries
	// ============================================================================
	// Get rate limit configuration for a group
	GetGroupConfig(ctx context.Context, chatID int64) (Group, error)
	// ============================================================================
	// Language Configuration Queries (Feature 007)
	// ============================================================================
	// Get the configured language for a group
	GetGroupLanguage(ctx context.Context, chatID int64) (string, error)
	// ============================================================================
	// LEGACY Queries (DISABLED - columns removed from groups table in migration 000003)
	// ============================================================================
	// LEGACY: GetChatLimit - columns 'char_limit', 'window_duration' removed from groups table
	// LEGACY: SetChatLimit - columns removed from groups table
	// ============================================================================
	// Group Membership Tracking Queries (Feature 011)
	// ============================================================================
	// Get membership record for user in group
	GetGroupMembership(ctx context.Context, arg GetGroupMembershipParams) (GroupMembership, error)
	// Get groups by exact title match - Feature 014: unified resolution (may return multiple)
	GetGroupsByTitle(ctx context.Context, title *string) ([]GetGroupsByTitleRow, error)
	// Get groups that need periodic sync (next_sync_at < NOW)
	GetGroupsNeedingSync(ctx context.Context, limit int32) ([]GetGroupsNeedingSyncRow, error)
	// Get recent sync events for monitoring (last N events)
	GetRecentSyncEvents(ctx context.Context, limit int32) ([]GetRecentSyncEventsRow, error)
	// Find memberships not updated in last 48 hours (for metrics)
	GetStaleGroupMemberships(ctx context.Context) ([]GetStaleGroupMembershipsRow, error)
	// Resolve @username to user_id (case-insensitive lookup)
	GetUserByUsername(ctx context.Context, lower string) (int64, error)
	// ============================================================================
	// MyGroups Command Queries (Feature 013)
	// ============================================================================
	// Get paginated list of groups where user is an active member, with their role
	// Feature 014: Now includes username for enhanced display "Title (@username)"
	// Verifies FR-002, FR-003, FR-006, FR-009 from Feature 013 specification
	GetUserGroupsWithRole(ctx context.Context, arg GetUserGroupsWithRoleParams) ([]GetUserGroupsWithRoleRow, error)
	// Retrieve user's language preference for private responses (Feature 008)
	GetUserLanguage(ctx context.Context, userID int64) (*string, error)
	// GetMostViolatedWindow removed - no restriction table in simple design
	// Violations are not tracked; messages are just deleted when over limit
	// ============================================================================
	// REMOVED: Multi-Window Exemption Queries (table removed in migration 000007)
	// ============================================================================
	// REMOVED: IsUserExemptFromWindow - exemptions table removed
	// Note: Use user_overrides table with /override command instead
	// ============================================================================
	// User Overrides (3-State Manual Control)
	// ============================================================================
	// Get manual override state for a user (NULL=follow rate limiter, TRUE=whitelist, FALSE=blacklist)
	GetUserOverride(ctx context.Context, arg GetUserOverrideParams) (GetUserOverrideRow, error)
	// Get current usage statistics for all windows for a user (for /mystatus command)
	// All windows share the same message log, each window calculates usage based on its time window
	GetUserWindowStats(ctx context.Context, arg GetUserWindowStatsParams) ([]GetUserWindowStatsRow, error)
	// Reverse lookup: get username from user_id (for display purposes)
	GetUsernameByUserID(ctx context.Context, userID int64) (*string, error)
	// Get specific window configuration
	GetWindowSlot(ctx context.Context, arg GetWindowSlotParams) (WindowSlot, error)
	// Warning levels are now calculated on-demand from current usage
	// No need to store them in database
	// GetAllWindowStates removed - replaced by GetUserWindowStats which uses messages table
	// ============================================================================
	// Multi-Window Evaluation (No Restriction Table Needed!)
	// ============================================================================
	// With simple design, restriction is calculated on-demand:
	// User is "restricted" when: current_usage + new_message_length > limit
	// No need to store restriction state!
	// ============================================================================
	// Multi-Window Statistics Queries
	// ============================================================================
	// Get statistics for a specific window from simple_messages table
	// All windows share the same message log, filtered by the window's time range
	GetWindowStats(ctx context.Context, arg GetWindowStatsParams) (GetWindowStatsRow, error)
	// Calculate current usage for a window using sliding window
	// Returns sum of char_count for all messages within the time window
	// All windows share the same message log, filtered by time window
	GetWindowUsage(ctx context.Context, arg GetWindowUsageParams) (int32, error)
	// Check if a group's rate limiting is paused
	IsGroupPaused(ctx context.Context, chatID int64) (IsGroupPausedRow, error)
	// Get language preferences for all groups (for cache initialization)
	ListAllGroupLanguages(ctx context.Context) ([]ListAllGroupLanguagesRow, error)
	// ============================================================================
	// Multi-Window State Tracking Queries
	// ============================================================================
	// GetWindowState removed - no longer needed with simple messages design
	// Current usage is calculated on-demand via GetWindowUsage
	// Record a message for sliding window calculation (one row per message, shared across all windows)
	RecordMessage(ctx context.Context, arg RecordMessageParams) error
	// Create audit trail entry for sync operation
	RecordSyncEvent(ctx context.Context, arg RecordSyncEventParams) (SyncEvent, error)
	// Remove manual override (return to rate limiter control)
	RemoveUserOverride(ctx context.Context, arg RemoveUserOverrideParams) error
	// Reset all messages for a user in a chat (affects all windows)
	ResetWindowMessages(ctx context.Context, arg ResetWindowMessagesParams) error
	// Reset all messages for all users in a chat (affects all windows)
	ResetWindowMessagesForAll(ctx context.Context, chatID int64) error
	// Set the language preference for a group
	SetGroupLanguage(ctx context.Context, arg SetGroupLanguageParams) error
	// LEGACY: UpsertGroupConfig - columns char_limit, duration_value, duration_unit, window_duration removed from groups table
	// Pause or unpause rate limiting for a group
	SetGroupPaused(ctx context.Context, arg SetGroupPausedParams) error
	// Set the language preference for a user (Feature 009)
	SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error
	// Set manual override state for a user
	SetUserOverride(ctx context.Context, arg SetUserOverrideParams) error
	// Enable or disable a window (/enablewindow, /disablewindow commands)
	SetWindowEnabled(ctx context.Context, arg SetWindowEnabledParams) error
	// Update sync metadata after sync operation
	UpdateSyncMetadata(ctx context.Context, arg UpdateSyncMetadataParams) error
	// Update window configuration (/setwindow command)
	UpdateWindowSlot(ctx context.Context, arg UpdateWindowSlotParams) error
	// Insert or update membership record (idempotent)
	UpsertGroupMembership(ctx context.Context, arg UpsertGroupMembershipParams) (GroupMembership, error)
	// Complete SQLC queries for all Storage interface methods
	// ============================================================================
	// LEGACY Message Tracking Queries (DISABLED - table removed in migration 000003)
	// ============================================================================
	// LEGACY: GetUserCurrentUsage - table 'messages' removed
	// LEGACY: StoreMessage - table 'messages' removed
	// LEGACY: DeleteOldMessages - table 'messages' removed
	// LEGACY: GetUserMessages - table 'messages' removed
	// LEGACY: DeleteUserMessages - table 'messages' removed
	// ============================================================================
	// User Management Queries
	// ============================================================================
	// Create or update a user record
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
